server:
  port: 0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/wjh-project
  application:
    name: chat-service
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@${eureka.instance.hostname}:8761/eureka/

gemini:
  version: v1beta
  modelName: gemini-1.5-flash
  url: https://generativelanguage.googleapis.com
  key: AIzaSyC1h1PM5gs-SHvYgiGrbeqCjl1XBQ94TOM
  constraint-prompt: "
  Please provide only the necessary information, followed the instruction !. 
  "
  fail-message: "I don't have enough ability to do this work !"
  checked-word: "CAN"
  check:
    text: "These are what you can do, just only give CAN or CANNOT for the next request! * Instruction: Give me all Porsche cars - Response: /vehicle-inventory/vehicles/porsche * Instruction: Give me all brands - Response: /vehicle-inventory/brands"
  response:
    text: "Just only give response if possible following these few-shot things, if receive an insufficient instruction, give the Response * Instruction: Give me all Porsche cars - Response: /vehicle-inventory/vehicles/porsche * Instruction: Give me all brands - Response: /vehicle-inventory/brands"

application:
  domain: http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html