server:
  port: 0

spring:
  application:
    name: vehicle-inventory-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: "root"
    password: "0941609091Th@"
    url: "jdbc:mysql://localhost:6606/VEHICLE_INVENTORY_SERVICE?useSSL=false&serverTimezone=UTC"
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@${eureka.instance.hostname}:8761/eureka/