server:
  port: 0

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


identity-provider:
  url: localhost:8180
  client-id: personal-project
  client-secret: bMV6RHv29VqNJrx1CEmaFS1CPighcamk

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@${eureka.instance.hostname}:8761/eureka/