server:
  port: 0

spring:
  application:
    name: search-service
#  data:
#    mongodb:
#      uri: mongodb://admin:admin@localhost:3303/notification-service?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/wjh-project
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

identity-provider:
  url: localhost:8180
  client-id: personal-project
  client-secret: bT4quORZtOYaCLmGP4ccCIMaRkA5gCJj

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@${eureka.instance.hostname}:8761/eureka/